import React, { CSSProperties } from "react";

import {
  Html,
  Body,
  Container,
  Text,
  Link,
  Preview,
  Tailwind,
} from "@react-email/components"; //We need to import a few components from @react-email/components

//We can also pass props to this react compnent

interface Props {
  name: string;
}
const WelcomeTemplate = ({ name }: Props) => {
  //   return <div>WelcomeTemplate</div>;n
  return (
    <Html>
      <Preview>Welcome Aboard {name}!</Preview>
      {/* Styling using custom CSS style attributes and properties witn in-line styles */}
      {/* <div> */}
      {/* // style={{
        //   display: "flex",
        //   //   justifyContent: "center",
        //   textAlign: "center",
        //   //   alignItems: "center",
        //   //   alignContent: "center",
        //   justifyItems: "center",
    //     }}
    //   > */}
      {/* <Body> */}
      {/* //   style={{
        //     // display: "inline-flex", */}
      {/* //     // display: "inline-block",
        //     color: "black",
        //     backgroundColor: "#D3D3D3",
        //     fontFamily: "monospace",
        //     borderStyle: "solid",
        //     borderRadius: "10px",
        //     stroke: "aliceblue",
        //   }}
        // > */}
      <div>
        <Tailwind>
          {/* <Body style={body}> Now instead of using the style prop we can actually use Tailwind Utility CSS Classnames to style our email template */}
          <Body className="bg-slate-200 text-color-black text-font-mono">
            {/* <Container style={container}> */}
            <Container className="border border-x-4 border-y-4 rounded-lg border-dashed border-orange-400">
              {/* <Text className="text-orange-700"> Tailwind CSS Utility classes are not getting applied to the email preview output generated by the preview-email application when it is initialized */}
              <Text className="font-mono text-5xl font-medium text-slate-600">
                Thanks for Signing Up to use my very first Next.Js app!
              </Text>

              <Link href="http://localhost:3000/cars">Explore our Cars</Link>
            </Container>
          </Body>
        </Tailwind>
      </div>
    </Html>
  );
};

export default WelcomeTemplate;

const body: CSSProperties = {
  color: "black",
  backgroundColor: "#D3D3D3",
  fontFamily: "monospace",
};

const heading: CSSProperties = {
  fontSize: "32px",
  fontStretch: "semi-expanded",
};
const container: CSSProperties = {
  borderWidth: "3px",
  borderStyle: "solid",
  borderColor: "coral",
  borderRadius: "10px",
  textWrap: "pretty",
};
